title: Default Page

columns:
  main:
    width: 2/3
    sections:
      testPages:
        type: pages
        templates: test
  sidebar:
    width: 1/3
    sections:
      pages:
        type: pages
        template: default
      files:
        type: files
